// Mock data for the Foster Care App - All 50 States with County Data

export const stateData = {
  alabama: {
    name: 'Alabama',
    totalChildren: 5809,
    licensedHomes: 2474,
    waitingForAdoption: 486,
    reunificationRate: 79.2,
    familyPreservationCases: 50
  },
  alaska: {
    name: 'Alaska',
    totalChildren: 2156,
    licensedHomes: 892,
    waitingForAdoption: 178,
    reunificationRate: 71.5,
    familyPreservationCases: 28
  },
  arizona: {
    name: 'Arizona',
    totalChildren: 14567,
    licensedHomes: 5823,
    waitingForAdoption: 1245,
    reunificationRate: 68.9,
    familyPreservationCases: 189
  },
  arkansas: {
    name: 'Arkansas',
    totalChildren: 4892,
    licensedHomes: 2156,
    waitingForAdoption: 398,
    reunificationRate: 77.8,
    familyPreservationCases: 67
  },
  california: {
    name: 'California',
    totalChildren: 58341,
    licensedHomes: 24567,
    waitingForAdoption: 4892,
    reunificationRate: 69.4,
    familyPreservationCases: 823
  },
  colorado: {
    name: 'Colorado',
    totalChildren: 6234,
    licensedHomes: 2789,
    waitingForAdoption: 534,
    reunificationRate: 74.6,
    familyPreservationCases: 98
  },
  connecticut: {
    name: 'Connecticut',
    totalChildren: 4123,
    licensedHomes: 1876,
    waitingForAdoption: 356,
    reunificationRate: 73.2,
    familyPreservationCases: 72
  },
  delaware: {
    name: 'Delaware',
    totalChildren: 1234,
    licensedHomes: 567,
    waitingForAdoption: 98,
    reunificationRate: 75.8,
    familyPreservationCases: 23
  },
  florida: {
    name: 'Florida',
    totalChildren: 23456,
    licensedHomes: 9876,
    waitingForAdoption: 2134,
    reunificationRate: 70.3,
    familyPreservationCases: 345
  },
  georgia: {
    name: 'Georgia',
    totalChildren: 13567,
    licensedHomes: 5678,
    waitingForAdoption: 1234,
    reunificationRate: 72.9,
    familyPreservationCases: 267
  },
  hawaii: {
    name: 'Hawaii',
    totalChildren: 2345,
    licensedHomes: 987,
    waitingForAdoption: 189,
    reunificationRate: 68.7,
    familyPreservationCases: 45
  },
  idaho: {
    name: 'Idaho',
    totalChildren: 2789,
    licensedHomes: 1234,
    waitingForAdoption: 234,
    reunificationRate: 76.5,
    familyPreservationCases: 52
  },
  illinois: {
    name: 'Illinois',
    totalChildren: 17234,
    licensedHomes: 7234,
    waitingForAdoption: 1567,
    reunificationRate: 71.8,
    familyPreservationCases: 298
  },
  indiana: {
    name: 'Indiana',
    totalChildren: 11234,
    licensedHomes: 4789,
    waitingForAdoption: 987,
    reunificationRate: 74.2,
    familyPreservationCases: 189
  },
  iowa: {
    name: 'Iowa',
    totalChildren: 5678,
    licensedHomes: 2456,
    waitingForAdoption: 456,
    reunificationRate: 78.3,
    familyPreservationCases: 89
  },
  kansas: {
    name: 'Kansas',
    totalChildren: 6789,
    licensedHomes: 2890,
    waitingForAdoption: 578,
    reunificationRate: 75.6,
    familyPreservationCases: 102
  },
  kentucky: {
    name: 'Kentucky',
    totalChildren: 8234,
    licensedHomes: 3456,
    waitingForAdoption: 723,
    reunificationRate: 76.9,
    familyPreservationCases: 134
  },
  louisiana: {
    name: 'Louisiana',
    totalChildren: 7892,
    licensedHomes: 3234,
    waitingForAdoption: 689,
    reunificationRate: 70.4,
    familyPreservationCases: 145
  },
  maine: {
    name: 'Maine',
    totalChildren: 2123,
    licensedHomes: 945,
    waitingForAdoption: 178,
    reunificationRate: 77.2,
    familyPreservationCases: 42
  },
  maryland: {
    name: 'Maryland',
    totalChildren: 4567,
    licensedHomes: 2012,
    waitingForAdoption: 389,
    reunificationRate: 72.8,
    familyPreservationCases: 87
  },
  massachusetts: {
    name: 'Massachusetts',
    totalChildren: 9876,
    licensedHomes: 4234,
    waitingForAdoption: 834,
    reunificationRate: 73.5,
    familyPreservationCases: 167
  },
  michigan: {
    name: 'Michigan',
    totalChildren: 12456,
    licensedHomes: 5234,
    waitingForAdoption: 1098,
    reunificationRate: 74.7,
    familyPreservationCases: 223
  },
  minnesota: {
    name: 'Minnesota',
    totalChildren: 7456,
    licensedHomes: 3234,
    waitingForAdoption: 634,
    reunificationRate: 76.4,
    familyPreservationCases: 128
  },
  mississippi: {
    name: 'Mississippi',
    totalChildren: 5234,
    licensedHomes: 2178,
    waitingForAdoption: 445,
    reunificationRate: 75.3,
    familyPreservationCases: 89
  },
  missouri: {
    name: 'Missouri',
    totalChildren: 13234,
    licensedHomes: 5567,
    waitingForAdoption: 1156,
    reunificationRate: 73.6,
    familyPreservationCases: 234
  },
  montana: {
    name: 'Montana',
    totalChildren: 2567,
    licensedHomes: 1123,
    waitingForAdoption: 212,
    reunificationRate: 74.9,
    familyPreservationCases: 48
  },
  nebraska: {
    name: 'Nebraska',
    totalChildren: 4123,
    licensedHomes: 1789,
    waitingForAdoption: 345,
    reunificationRate: 77.1,
    familyPreservationCases: 72
  },
  nevada: {
    name: 'Nevada',
    totalChildren: 5678,
    licensedHomes: 2345,
    waitingForAdoption: 478,
    reunificationRate: 69.8,
    familyPreservationCases: 98
  },
  "new-hampshire": {
    name: 'New Hampshire',
    totalChildren: 1456,
    licensedHomes: 634,
    waitingForAdoption: 123,
    reunificationRate: 78.5,
    familyPreservationCases: 28
  },
  "new-jersey": {
    name: 'New Jersey',
    totalChildren: 6789,
    licensedHomes: 2956,
    waitingForAdoption: 578,
    reunificationRate: 72.3,
    familyPreservationCases: 112
  },
  "new-mexico": {
    name: 'New Mexico',
    totalChildren: 3456,
    licensedHomes: 1478,
    waitingForAdoption: 289,
    reunificationRate: 71.7,
    familyPreservationCases: 67
  },
  "new-york": {
    name: 'New York',
    totalChildren: 18045,
    licensedHomes: 7420,
    waitingForAdoption: 934,
    reunificationRate: 76.3,
    familyPreservationCases: 320
  },
  "north-carolina": {
    name: 'North Carolina',
    totalChildren: 10234,
    licensedHomes: 4321,
    waitingForAdoption: 867,
    reunificationRate: 75.8,
    familyPreservationCases: 178
  },
  "north-dakota": {
    name: 'North Dakota',
    totalChildren: 1789,
    licensedHomes: 756,
    waitingForAdoption: 145,
    reunificationRate: 76.9,
    familyPreservationCases: 34
  },
  ohio: {
    name: 'Ohio',
    totalChildren: 15678,
    licensedHomes: 6543,
    waitingForAdoption: 1345,
    reunificationRate: 73.4,
    familyPreservationCases: 278
  },
  oklahoma: {
    name: 'Oklahoma',
    totalChildren: 9234,
    licensedHomes: 3876,
    waitingForAdoption: 789,
    reunificationRate: 72.6,
    familyPreservationCases: 167
  },
  oregon: {
    name: 'Oregon',
    totalChildren: 7345,
    licensedHomes: 3123,
    waitingForAdoption: 623,
    reunificationRate: 74.8,
    familyPreservationCases: 134
  },
  pennsylvania: {
    name: 'Pennsylvania',
    totalChildren: 14789,
    licensedHomes: 6234,
    waitingForAdoption: 1267,
    reunificationRate: 74.2,
    familyPreservationCases: 256
  },
  "rhode-island": {
    name: 'Rhode Island',
    totalChildren: 2012,
    licensedHomes: 867,
    waitingForAdoption: 167,
    reunificationRate: 73.9,
    familyPreservationCases: 39
  },
  "south-carolina": {
    name: 'South Carolina',
    totalChildren: 4567,
    licensedHomes: 1923,
    waitingForAdoption: 389,
    reunificationRate: 74.7,
    familyPreservationCases: 82
  },
  "south-dakota": {
    name: 'South Dakota',
    totalChildren: 1678,
    licensedHomes: 723,
    waitingForAdoption: 134,
    reunificationRate: 77.4,
    familyPreservationCases: 32
  },
  tennessee: {
    name: 'Tennessee',
    totalChildren: 8456,
    licensedHomes: 3567,
    waitingForAdoption: 723,
    reunificationRate: 75.6,
    familyPreservationCases: 145
  },
  texas: {
    name: 'Texas',
    totalChildren: 29876,
    licensedHomes: 12345,
    waitingForAdoption: 2567,
    reunificationRate: 71.2,
    familyPreservationCases: 489
  },
  utah: {
    name: 'Utah',
    totalChildren: 2890,
    licensedHomes: 1234,
    waitingForAdoption: 245,
    reunificationRate: 76.8,
    familyPreservationCases: 56
  },
  vermont: {
    name: 'Vermont',
    totalChildren: 1123,
    licensedHomes: 489,
    waitingForAdoption: 89,
    reunificationRate: 78.9,
    familyPreservationCases: 21
  },
  virginia: {
    name: 'Virginia',
    totalChildren: 5678,
    licensedHomes: 2456,
    waitingForAdoption: 478,
    reunificationRate: 75.3,
    familyPreservationCases: 98
  },
  washington: {
    name: 'Washington',
    totalChildren: 9345,
    licensedHomes: 3978,
    waitingForAdoption: 789,
    reunificationRate: 73.7,
    familyPreservationCases: 167
  },
  "west-virginia": {
    name: 'West Virginia',
    totalChildren: 6789,
    licensedHomes: 2845,
    waitingForAdoption: 578,
    reunificationRate: 74.5,
    familyPreservationCases: 123
  },
  wisconsin: {
    name: 'Wisconsin',
    totalChildren: 7234,
    licensedHomes: 3098,
    waitingForAdoption: 612,
    reunificationRate: 76.2,
    familyPreservationCases: 134
  },
  wyoming: {
    name: 'Wyoming',
    totalChildren: 1345,
    licensedHomes: 578,
    waitingForAdoption: 112,
    reunificationRate: 77.8,
    familyPreservationCases: 26
  }
};


export const countyData = {
  // ==================== ALABAMA COUNTIES ====================
  'butler-al': {
    name: 'Butler County, Alabama',
    state: 'Alabama',
    population: 18832,
    totalChurches: 5,
    childrenInCare: 21,
    childrenInFamily: 34,
    childrenInKinship: 28,
    childrenOutOfCounty: 4,
    licensedHomes: 43,
    licensedHomesPerChild: 2.04,
    waitingForAdoption: 5,
    childrenAdopted2024: 6,
    avgMonthsToAdoption: 8.4,
    familyPreservationCases: 12,
    reunificationRate: 85,
    churchesProvidingSupport: 4,
    supportPercentage: 80
  },
  'jefferson-al': {
    name: 'Jefferson County, Alabama',
    state: 'Alabama',
    population: 674721,
    totalChurches: 312,
    childrenInCare: 892,
    childrenInFamily: 456,
    childrenInKinship: 298,
    childrenOutOfCounty: 67,
    licensedHomes: 534,
    licensedHomesPerChild: 0.60,
    waitingForAdoption: 89,
    childrenAdopted2024: 67,
    avgMonthsToAdoption: 11.2,
    familyPreservationCases: 145,
    reunificationRate: 78,
    churchesProvidingSupport: 234,
    supportPercentage: 75
  },
  'mobile-al': {
    name: 'Mobile County, Alabama',
    state: 'Alabama',
    population: 413210,
    totalChurches: 189,
    childrenInCare: 567,
    childrenInFamily: 289,
    childrenInKinship: 198,
    childrenOutOfCounty: 45,
    licensedHomes: 334,
    licensedHomesPerChild: 0.59,
    waitingForAdoption: 56,
    childrenAdopted2024: 43,
    avgMonthsToAdoption: 10.8,
    familyPreservationCases: 89,
    reunificationRate: 81,
    churchesProvidingSupport: 142,
    supportPercentage: 75
  },
  'montgomery-al': {
    name: 'Montgomery County, Alabama',
    state: 'Alabama',
    population: 228954,
    totalChurches: 145,
    childrenInCare: 423,
    childrenInFamily: 213,
    childrenInKinship: 156,
    childrenOutOfCounty: 34,
    licensedHomes: 267,
    licensedHomesPerChild: 0.63,
    waitingForAdoption: 45,
    childrenAdopted2024: 38,
    avgMonthsToAdoption: 9.6,
    familyPreservationCases: 67,
    reunificationRate: 79,
    churchesProvidingSupport: 108,
    supportPercentage: 74
  },

  // ==================== NEW YORK COUNTIES ====================
  'nassau-ny': {
    name: 'Nassau County, New York',
    state: 'New York',
    population: 1395774,
    totalChurches: 127,
    childrenInCare: 543,
    childrenInFamily: 234,
    childrenInKinship: 189,
    childrenOutOfCounty: 15,
    licensedHomes: 289,
    licensedHomesPerChild: 0.53,
    waitingForAdoption: 67,
    childrenAdopted2024: 45,
    avgMonthsToAdoption: 12.3,
    familyPreservationCases: 156,
    reunificationRate: 72,
    churchesProvidingSupport: 89,
    supportPercentage: 70
  },
  'suffolk-ny': {
    name: 'Suffolk County, New York',
    state: 'New York',
    population: 1525920,
    totalChurches: 198,
    childrenInCare: 678,
    childrenInFamily: 312,
    childrenInKinship: 234,
    childrenOutOfCounty: 23,
    licensedHomes: 367,
    licensedHomesPerChild: 0.54,
    waitingForAdoption: 78,
    childrenAdopted2024: 56,
    avgMonthsToAdoption: 11.8,
    familyPreservationCases: 189,
    reunificationRate: 74,
    churchesProvidingSupport: 145,
    supportPercentage: 73
  },
  'erie-ny': {
    name: 'Erie County, New York',
    state: 'New York',
    population: 954236,
    totalChurches: 234,
    childrenInCare: 823,
    childrenInFamily: 423,
    childrenInKinship: 267,
    childrenOutOfCounty: 45,
    licensedHomes: 456,
    licensedHomesPerChild: 0.55,
    waitingForAdoption: 92,
    childrenAdopted2024: 67,
    avgMonthsToAdoption: 12.1,
    familyPreservationCases: 178,
    reunificationRate: 75,
    churchesProvidingSupport: 176,
    supportPercentage: 75
  },
  'westchester-ny': {
    name: 'Westchester County, New York',
    state: 'New York',
    population: 1004457,
    totalChurches: 156,
    childrenInCare: 456,
    childrenInFamily: 234,
    childrenInKinship: 178,
    childrenOutOfCounty: 18,
    licensedHomes: 289,
    licensedHomesPerChild: 0.63,
    waitingForAdoption: 56,
    childrenAdopted2024: 42,
    avgMonthsToAdoption: 11.4,
    familyPreservationCases: 123,
    reunificationRate: 77,
    churchesProvidingSupport: 112,
    supportPercentage: 72
  },

  // ==================== CALIFORNIA COUNTIES ====================
  'los-angeles-ca': {
    name: 'Los Angeles County, California',
    state: 'California',
    population: 10014009,
    totalChurches: 2156,
    childrenInCare: 18234,
    childrenInFamily: 7892,
    childrenInKinship: 5634,
    childrenOutOfCounty: 234,
    licensedHomes: 4567,
    licensedHomesPerChild: 0.25,
    waitingForAdoption: 1234,
    childrenAdopted2024: 892,
    avgMonthsToAdoption: 15.7,
    familyPreservationCases: 2345,
    reunificationRate: 68,
    churchesProvidingSupport: 1523,
    supportPercentage: 71
  },
  'san-diego-ca': {
    name: 'San Diego County, California',
    state: 'California',
    population: 3298634,
    totalChurches: 876,
    childrenInCare: 5678,
    childrenInFamily: 2456,
    childrenInKinship: 1789,
    childrenOutOfCounty: 123,
    licensedHomes: 1456,
    licensedHomesPerChild: 0.26,
    waitingForAdoption: 423,
    childrenAdopted2024: 298,
    avgMonthsToAdoption: 14.2,
    familyPreservationCases: 789,
    reunificationRate: 70,
    churchesProvidingSupport: 623,
    supportPercentage: 71
  },
  'orange-ca': {
    name: 'Orange County, California',
    state: 'California',
    population: 3186989,
    totalChurches: 789,
    childrenInCare: 4234,
    childrenInFamily: 1876,
    childrenInKinship: 1345,
    childrenOutOfCounty: 98,
    licensedHomes: 1123,
    licensedHomesPerChild: 0.27,
    waitingForAdoption: 356,
    childrenAdopted2024: 245,
    avgMonthsToAdoption: 13.8,
    familyPreservationCases: 623,
    reunificationRate: 69,
    churchesProvidingSupport: 567,
    supportPercentage: 72
  },
  'riverside-ca': {
    name: 'Riverside County, California',
    state: 'California',
    population: 2470546,
    totalChurches: 534,
    childrenInCare: 3456,
    childrenInFamily: 1567,
    childrenInKinship: 1123,
    childrenOutOfCounty: 89,
    licensedHomes: 923,
    licensedHomesPerChild: 0.27,
    waitingForAdoption: 289,
    childrenAdopted2024: 198,
    avgMonthsToAdoption: 14.5,
    familyPreservationCases: 512,
    reunificationRate: 68,
    churchesProvidingSupport: 378,
    supportPercentage: 71
  },

  // ==================== TEXAS COUNTIES ====================
  'harris-tx': {
    name: 'Harris County, Texas',
    state: 'Texas',
    population: 4731145,
    totalChurches: 1234,
    childrenInCare: 8901,
    childrenInFamily: 3456,
    childrenInKinship: 2789,
    childrenOutOfCounty: 189,
    licensedHomes: 3234,
    licensedHomesPerChild: 0.36,
    waitingForAdoption: 723,
    childrenAdopted2024: 456,
    avgMonthsToAdoption: 13.8,
    familyPreservationCases: 1234,
    reunificationRate: 70,
    churchesProvidingSupport: 876,
    supportPercentage: 71
  },
  'dallas-tx': {
    name: 'Dallas County, Texas',
    state: 'Texas',
    population: 2613539,
    totalChurches: 876,
    childrenInCare: 6234,
    childrenInFamily: 2789,
    childrenInKinship: 1923,
    childrenOutOfCounty: 145,
    licensedHomes: 2156,
    licensedHomesPerChild: 0.35,
    waitingForAdoption: 534,
    childrenAdopted2024: 367,
    avgMonthsToAdoption: 13.2,
    familyPreservationCases: 892,
    reunificationRate: 71,
    churchesProvidingSupport: 623,
    supportPercentage: 71
  },
  'bexar-tx': {
    name: 'Bexar County, Texas',
    state: 'Texas',
    population: 2009324,
    totalChurches: 723,
    childrenInCare: 4567,
    childrenInFamily: 2012,
    childrenInKinship: 1456,
    childrenOutOfCounty: 112,
    licensedHomes: 1678,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 398,
    childrenAdopted2024: 267,
    avgMonthsToAdoption: 12.9,
    familyPreservationCases: 678,
    reunificationRate: 72,
    churchesProvidingSupport: 512,
    supportPercentage: 71
  },
  'travis-tx': {
    name: 'Travis County, Texas',
    state: 'Texas',
    population: 1318652,
    totalChurches: 456,
    childrenInCare: 2789,
    childrenInFamily: 1234,
    childrenInKinship: 892,
    childrenOutOfCounty: 78,
    licensedHomes: 1023,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 234,
    childrenAdopted2024: 178,
    avgMonthsToAdoption: 12.6,
    familyPreservationCases: 423,
    reunificationRate: 73,
    churchesProvidingSupport: 334,
    supportPercentage: 73
  },

  // ==================== ILLINOIS COUNTIES ====================
  'cook-il': {
    name: 'Cook County, Illinois',
    state: 'Illinois',
    population: 5275541,
    totalChurches: 987,
    childrenInCare: 5678,
    childrenInFamily: 2345,
    childrenInKinship: 1876,
    childrenOutOfCounty: 123,
    licensedHomes: 2134,
    licensedHomesPerChild: 0.38,
    waitingForAdoption: 478,
    childrenAdopted2024: 312,
    avgMonthsToAdoption: 14.2,
    familyPreservationCases: 876,
    reunificationRate: 71,
    churchesProvidingSupport: 698,
    supportPercentage: 71
  },
  'dupage-il': {
    name: 'DuPage County, Illinois',
    state: 'Illinois',
    population: 932675,
    totalChurches: 234,
    childrenInCare: 1234,
    childrenInFamily: 567,
    childrenInKinship: 423,
    childrenOutOfCounty: 34,
    licensedHomes: 478,
    licensedHomesPerChild: 0.39,
    waitingForAdoption: 98,
    childrenAdopted2024: 67,
    avgMonthsToAdoption: 13.5,
    familyPreservationCases: 189,
    reunificationRate: 73,
    churchesProvidingSupport: 167,
    supportPercentage: 71
  },
  'lake-il': {
    name: 'Lake County, Illinois',
    state: 'Illinois',
    population: 714342,
    totalChurches: 198,
    childrenInCare: 1023,
    childrenInFamily: 478,
    childrenInKinship: 356,
    childrenOutOfCounty: 28,
    licensedHomes: 398,
    licensedHomesPerChild: 0.39,
    waitingForAdoption: 82,
    childrenAdopted2024: 56,
    avgMonthsToAdoption: 13.1,
    familyPreservationCases: 156,
    reunificationRate: 72,
    churchesProvidingSupport: 142,
    supportPercentage: 72
  },

  // ==================== FLORIDA COUNTIES ====================
  'miami-dade-fl': {
    name: 'Miami-Dade County, Florida',
    state: 'Florida',
    population: 2716940,
    totalChurches: 923,
    childrenInCare: 6789,
    childrenInFamily: 2892,
    childrenInKinship: 2156,
    childrenOutOfCounty: 178,
    licensedHomes: 2456,
    licensedHomesPerChild: 0.36,
    waitingForAdoption: 567,
    childrenAdopted2024: 389,
    avgMonthsToAdoption: 13.9,
    familyPreservationCases: 923,
    reunificationRate: 69,
    churchesProvidingSupport: 656,
    supportPercentage: 71
  },
  'broward-fl': {
    name: 'Broward County, Florida',
    state: 'Florida',
    population: 1952778,
    totalChurches: 678,
    childrenInCare: 4567,
    childrenInFamily: 1923,
    childrenInKinship: 1456,
    childrenOutOfCounty: 123,
    licensedHomes: 1678,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 389,
    childrenAdopted2024: 267,
    avgMonthsToAdoption: 13.4,
    familyPreservationCases: 634,
    reunificationRate: 70,
    churchesProvidingSupport: 478,
    supportPercentage: 71
  },
  'palm-beach-fl': {
    name: 'Palm Beach County, Florida',
    state: 'Florida',
    population: 1496770,
    totalChurches: 534,
    childrenInCare: 3456,
    childrenInFamily: 1456,
    childrenInKinship: 1098,
    childrenOutOfCounty: 98,
    licensedHomes: 1267,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 298,
    childrenAdopted2024: 203,
    avgMonthsToAdoption: 13.1,
    familyPreservationCases: 478,
    reunificationRate: 71,
    churchesProvidingSupport: 378,
    supportPercentage: 71
  },

  // ==================== OHIO COUNTIES ====================
  'cuyahoga-oh': {
    name: 'Cuyahoga County, Ohio',
    state: 'Ohio',
    population: 1264817,
    totalChurches: 456,
    childrenInCare: 3234,
    childrenInFamily: 1456,
    childrenInKinship: 1023,
    childrenOutOfCounty: 89,
    licensedHomes: 1234,
    licensedHomesPerChild: 0.38,
    waitingForAdoption: 267,
    childrenAdopted2024: 189,
    avgMonthsToAdoption: 13.7,
    familyPreservationCases: 456,
    reunificationRate: 72,
    churchesProvidingSupport: 323,
    supportPercentage: 71
  },
  'franklin-oh': {
    name: 'Franklin County, Ohio',
    state: 'Ohio',
    population: 1323807,
    totalChurches: 487,
    childrenInCare: 3456,
    childrenInFamily: 1567,
    childrenInKinship: 1098,
    childrenOutOfCounty: 92,
    licensedHomes: 1323,
    licensedHomesPerChild: 0.38,
    waitingForAdoption: 289,
    childrenAdopted2024: 198,
    avgMonthsToAdoption: 13.4,
    familyPreservationCases: 489,
    reunificationRate: 73,
    churchesProvidingSupport: 345,
    supportPercentage: 71
  },
  'hamilton-oh': {
    name: 'Hamilton County, Ohio',
    state: 'Ohio',
    population: 830639,
    totalChurches: 367,
    childrenInCare: 2456,
    childrenInFamily: 1098,
    childrenInKinship: 789,
    childrenOutOfCounty: 67,
    licensedHomes: 923,
    licensedHomesPerChild: 0.38,
    waitingForAdoption: 203,
    childrenAdopted2024: 145,
    avgMonthsToAdoption: 13.2,
    familyPreservationCases: 356,
    reunificationRate: 74,
    churchesProvidingSupport: 267,
    supportPercentage: 73
  },

  // ==================== PENNSYLVANIA COUNTIES ====================
  'philadelphia-pa': {
    name: 'Philadelphia County, Pennsylvania',
    state: 'Pennsylvania',
    population: 1584064,
    totalChurches: 623,
    childrenInCare: 4234,
    childrenInFamily: 1892,
    childrenInKinship: 1345,
    childrenOutOfCounty: 112,
    licensedHomes: 1567,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 356,
    childrenAdopted2024: 245,
    avgMonthsToAdoption: 14.1,
    familyPreservationCases: 623,
    reunificationRate: 73,
    churchesProvidingSupport: 445,
    supportPercentage: 71
  },
  'allegheny-pa': {
    name: 'Allegheny County, Pennsylvania',
    state: 'Pennsylvania',
    population: 1250578,
    totalChurches: 534,
    childrenInCare: 3567,
    childrenInFamily: 1598,
    childrenInKinship: 1134,
    childrenOutOfCounty: 95,
    licensedHomes: 1323,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 298,
    childrenAdopted2024: 208,
    avgMonthsToAdoption: 13.8,
    familyPreservationCases: 523,
    reunificationRate: 74,
    churchesProvidingSupport: 378,
    supportPercentage: 71
  },
  'montgomery-pa': {
    name: 'Montgomery County, Pennsylvania',
    state: 'Pennsylvania',
    population: 856553,
    totalChurches: 398,
    childrenInCare: 2234,
    childrenInFamily: 998,
    childrenInKinship: 712,
    childrenOutOfCounty: 62,
    licensedHomes: 823,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 187,
    childrenAdopted2024: 134,
    avgMonthsToAdoption: 13.3,
    familyPreservationCases: 334,
    reunificationRate: 75,
    churchesProvidingSupport: 289,
    supportPercentage: 73
  },

  // ==================== GEORGIA COUNTIES ====================
  'fulton-ga': {
    name: 'Fulton County, Georgia',
    state: 'Georgia',
    population: 1066710,
    totalChurches: 467,
    childrenInCare: 2892,
    childrenInFamily: 1298,
    childrenInKinship: 923,
    childrenOutOfCounty: 78,
    licensedHomes: 1067,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 242,
    childrenAdopted2024: 167,
    avgMonthsToAdoption: 13.5,
    familyPreservationCases: 423,
    reunificationRate: 72,
    churchesProvidingSupport: 334,
    supportPercentage: 72
  },
  'gwinnett-ga': {
    name: 'Gwinnett County, Georgia',
    state: 'Georgia',
    population: 957062,
    totalChurches: 412,
    childrenInCare: 2456,
    childrenInFamily: 1098,
    childrenInKinship: 782,
    childrenOutOfCounty: 65,
    licensedHomes: 908,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 205,
    childrenAdopted2024: 142,
    avgMonthsToAdoption: 13.1,
    familyPreservationCases: 356,
    reunificationRate: 73,
    churchesProvidingSupport: 298,
    supportPercentage: 72
  },
  'cobb-ga': {
    name: 'Cobb County, Georgia',
    state: 'Georgia',
    population: 766149,
    totalChurches: 356,
    childrenInCare: 1987,
    childrenInFamily: 889,
    childrenInKinship: 634,
    childrenOutOfCounty: 53,
    licensedHomes: 734,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 166,
    childrenAdopted2024: 115,
    avgMonthsToAdoption: 12.9,
    familyPreservationCases: 289,
    reunificationRate: 74,
    churchesProvidingSupport: 256,
    supportPercentage: 72
  },

  // ==================== MICHIGAN COUNTIES ====================
  'wayne-mi': {
    name: 'Wayne County, Michigan',
    state: 'Michigan',
    population: 1793561,
    totalChurches: 678,
    childrenInCare: 4123,
    childrenInFamily: 1845,
    childrenInKinship: 1312,
    childrenOutOfCounty: 109,
    licensedHomes: 1523,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 345,
    childrenAdopted2024: 237,
    avgMonthsToAdoption: 14.3,
    familyPreservationCases: 601,
    reunificationRate: 73,
    churchesProvidingSupport: 482,
    supportPercentage: 71
  },
  'oakland-mi': {
    name: 'Oakland County, Michigan',
    state: 'Michigan',
    population: 1274395,
    totalChurches: 512,
    childrenInCare: 2789,
    childrenInFamily: 1248,
    childrenInKinship: 888,
    childrenOutOfCounty: 74,
    licensedHomes: 1031,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 233,
    childrenAdopted2024: 161,
    avgMonthsToAdoption: 13.6,
    familyPreservationCases: 407,
    reunificationRate: 75,
    churchesProvidingSupport: 364,
    supportPercentage: 71
  },
  'macomb-mi': {
    name: 'Macomb County, Michigan',
    state: 'Michigan',
    population: 881217,
    totalChurches: 398,
    childrenInCare: 2134,
    childrenInFamily: 955,
    childrenInKinship: 679,
    childrenOutOfCounty: 57,
    licensedHomes: 789,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 178,
    childrenAdopted2024: 123,
    avgMonthsToAdoption: 13.3,
    familyPreservationCases: 311,
    reunificationRate: 74,
    churchesProvidingSupport: 283,
    supportPercentage: 71
  },

  // ==================== NORTH CAROLINA COUNTIES ====================
  'mecklenburg-nc': {
    name: 'Mecklenburg County, North Carolina',
    state: 'North Carolina',
    population: 1115482,
    totalChurches: 489,
    childrenInCare: 2678,
    childrenInFamily: 1198,
    childrenInKinship: 852,
    childrenOutOfCounty: 71,
    licensedHomes: 990,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 224,
    childrenAdopted2024: 155,
    avgMonthsToAdoption: 13.4,
    familyPreservationCases: 390,
    reunificationRate: 75,
    churchesProvidingSupport: 348,
    supportPercentage: 71
  },
  'wake-nc': {
    name: 'Wake County, North Carolina',
    state: 'North Carolina',
    population: 1129410,
    totalChurches: 501,
    childrenInCare: 2734,
    childrenInFamily: 1223,
    childrenInKinship: 871,
    childrenOutOfCounty: 72,
    licensedHomes: 1011,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 229,
    childrenAdopted2024: 158,
    avgMonthsToAdoption: 13.2,
    familyPreservationCases: 398,
    reunificationRate: 76,
    churchesProvidingSupport: 356,
    supportPercentage: 71
  },
  'guilford-nc': {
    name: 'Guilford County, North Carolina',
    state: 'North Carolina',
    population: 541299,
    totalChurches: 298,
    childrenInCare: 1634,
    childrenInFamily: 731,
    childrenInKinship: 520,
    childrenOutOfCounty: 43,
    licensedHomes: 604,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 137,
    childrenAdopted2024: 94,
    avgMonthsToAdoption: 13.0,
    familyPreservationCases: 238,
    reunificationRate: 76,
    churchesProvidingSupport: 212,
    supportPercentage: 71
  },

  // ==================== ARIZONA COUNTIES ====================
  'maricopa-az': {
    name: 'Maricopa County, Arizona',
    state: 'Arizona',
    population: 4485414,
    totalChurches: 1089,
    childrenInCare: 10234,
    childrenInFamily: 4578,
    childrenInKinship: 3256,
    childrenOutOfCounty: 271,
    licensedHomes: 3786,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 856,
    childrenAdopted2024: 591,
    avgMonthsToAdoption: 14.5,
    familyPreservationCases: 1490,
    reunificationRate: 68,
    churchesProvidingSupport: 774,
    supportPercentage: 71
  },
  'pima-az': {
    name: 'Pima County, Arizona',
    state: 'Arizona',
    population: 1043433,
    totalChurches: 412,
    childrenInCare: 2567,
    childrenInFamily: 1148,
    childrenInKinship: 817,
    childrenOutOfCounty: 68,
    licensedHomes: 949,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 215,
    childrenAdopted2024: 148,
    avgMonthsToAdoption: 13.9,
    familyPreservationCases: 374,
    reunificationRate: 69,
    churchesProvidingSupport: 293,
    supportPercentage: 71
  },
  'pinal-az': {
    name: 'Pinal County, Arizona',
    state: 'Arizona',
    population: 462967,
    totalChurches: 198,
    childrenInCare: 1234,
    childrenInFamily: 552,
    childrenInKinship: 393,
    childrenOutOfCounty: 33,
    licensedHomes: 456,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 103,
    childrenAdopted2024: 71,
    avgMonthsToAdoption: 13.5,
    familyPreservationCases: 180,
    reunificationRate: 69,
    churchesProvidingSupport: 141,
    supportPercentage: 71
  },

  // ==================== WASHINGTON COUNTIES ====================
  'king-wa': {
    name: 'King County, Washington',
    state: 'Washington',
    population: 2269675,
    totalChurches: 734,
    childrenInCare: 4567,
    childrenInFamily: 2043,
    childrenInKinship: 1454,
    childrenOutOfCounty: 121,
    licensedHomes: 1689,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 382,
    childrenAdopted2024: 263,
    avgMonthsToAdoption: 13.8,
    familyPreservationCases: 665,
    reunificationRate: 73,
    churchesProvidingSupport: 521,
    supportPercentage: 71
  },
  'pierce-wa': {
    name: 'Pierce County, Washington',
    state: 'Washington',
    population: 921130,
    totalChurches: 398,
    childrenInCare: 2234,
    childrenInFamily: 999,
    childrenInKinship: 711,
    childrenOutOfCounty: 59,
    licensedHomes: 826,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 187,
    childrenAdopted2024: 129,
    avgMonthsToAdoption: 13.4,
    familyPreservationCases: 325,
    reunificationRate: 74,
    churchesProvidingSupport: 283,
    supportPercentage: 71
  },
  'snohomish-wa': {
    name: 'Snohomish County, Washington',
    state: 'Washington',
    population: 827957,
    totalChurches: 356,
    childrenInCare: 2001,
    childrenInFamily: 895,
    childrenInKinship: 637,
    childrenOutOfCounty: 53,
    licensedHomes: 740,
    licensedHomesPerChild: 0.37,
    waitingForAdoption: 167,
    childrenAdopted2024: 115,
    avgMonthsToAdoption: 13.2,
    familyPreservationCases: 291,
    reunificationRate: 74,
    churchesProvidingSupport: 253,
    supportPercentage: 71
  }
};


export const organizations = [
  {
    name: 'Bridge Ministry',
    type: 'Bridge Ministry',
    category: 'Faith Community Alliance',
    description: 'Supporting foster families through faith-based community connections and practical assistance.',
    areas: ['Foster and Kinship Families', 'Wraparound'],
    county: 'Nassau County - 11010',
    phone: '516-456-7891',
    email: 'info@nassaubridgeministry.org'
  },
  {
    name: 'Hope Family Services',
    type: 'Service Organization',
    category: 'Hope Family Services',
    description: 'Supporting foster families through faith-based community connections and practical assistance.',
    areas: ['Adoptive', 'Wraparound', 'Biological'],
    county: 'Nassau County - 11010',
    phone: '516-456-7891',
    email: 'info@hopefamily.org'
  },
  {
    name: 'Community Support Network',
    type: 'Government',
    category: 'Community Support Network',
    description: 'Supporting foster families through faith-based community connections and practical assistance.',
    areas: ['Foster and Kinship Families', 'Wraparound'],
    county: 'Nassau County - 11010',
    phone: '516-456-7891',
    email: 'info@nassaucommunity.org'
  }
];

export const nationalStats = {
  childrenInCare: 343077,
  childrenInFamilyFoster: 52483,
  childrenInKinship: 74208,
  childrenWaitingAdoption: 48459,
  childrenAdopted2023: 50193,
  totalChurches: 370000,
  churchesWithMinistry: 30000
};